Settings:
  Prefix: '&7[&dEpicSellChest&7]: ' #The prefix before all messages from the plugin.
  Metrics: true #If the plugin is allowed to send server data to MCUpdate.com anonymously.
  Check-For-Updates: true #If the plugin will check for updates.
  Base-Price: 10 #The base price for the items being sold.
  Base-Currency: Vault #The base currency being used when selling items.
  Allow-Damaged-Items: true #Toggle if players can sell damaged items.
  Use-Two-Factor-Auth: true #Toggle if the player has to do the command again to confirm the sell.
  Custom-Currencies: #List of custom currencies that you can make. If you wish to not use them leave as it and just don't use it in the prices.
    Vault:
      Command: 'eco give %player% %cost%'
    Gold_Ingot:
      Command: 'give %player% goldingot %cost%'
  Chest-Selling-Item:
    Item: 'QUARTZ' #The item the chest selling item will be.
    Name: '&5&lEpic Selling Wand' #The name of the item.
    Lore: #The lore of the item.
      - '&7The Epic Selling Wand sells the'
      - '&7chest that you right click with it.'
      - ''
      - '&7&l(&4&l!&7&l) &7Right click a chest to sell it.'
    Glowing: true #If the item has an enchanted glowing effect.
  Selling-Options:
    Price-Selling-Only: false #Sell only items that have a price.
  Region-Options: #All the options regarding regions.
    Max-Block-Area: 5000 #The max amount of blocks in the region a player can have.
    Chest-Sell-Toggle: true #Toggle if players have max chests that can be sold in a region.
    Max-Chest-Sell: 50 #The max amount of chests players can sell in a region. It ignores any chests that are empty or just have blacklisted items.
  Sign-Options:
    Toggle: true #Toggle if players can make signs. The player must have this permission: epicsellchest.sign
    Inventory-Name: '&7&l>&8&l> &8Auto Sell' #The name of the inventory when the player sells from a sign.
    Sign-Maker: '{SellChest}' #The line the player puts at the top to make a sign.
    Two-Factor-Auth-Options: #The options for the signs if the two factor auth option is on.
      Inventory-Name: '&7&l>&8&l> &8Two Factor Authentication' #The name of the inventory that opens.
      Accept: #The item for the accept button.
        Item: 'STAINED_GLASS_PANE:5'
        Name: '&a&lAccept'
        Lore:
          - '&7Click this option to sell all items.'
          - '&7&l(&c&l!&7&l) &cClosing this inventory will auto sell.'
      Info: #The item for the Info button.
        Item: 'STAINED_GLASS_PANE:7'
        Name: '&6&lInformation'
        Lore:
          - ''
          - '          &a<--- Sell the inventory'
          - '       &cDon''t sell the inventory --->'
          - ''
          - '&7&l(&c&l!&7&l) &cClosing this inventory will auto sell.'
      Deny: #The item for the deny button.
        Item: 'STAINED_GLASS_PANE:14'
        Name: '&c&lDeny'
        Lore:
          - '&7Click this option to get your items back.'
          - '&7&l(&c&l!&7&l) &cClosing this inventory will auto sell.'
    Lines: #When a sign is made what the lines will be.
      1: '&8[&7Auto-Sell&8]'
      2: 'Click here to sell'
      3: 'your items you'
      4: 'don''t want.'
  Black-List-Items: #Black listed items that can't be sold.
    - 'BEDROCK' #BedRock
    - 'SPONGE' #Sponge
  Black-List-Enchantments: {} #Use like the normal Black-List option if using it this.
  Enchantment-Cost: #The extra "Currency" each enchantment level gives to an item.
    #If you wish not to give extra make it like this "Enchantment-Cost: {}" and remove all enchantments.
    KNOCKBACK: #The enchantment which gives more "Currency"
      - 'Level:1, Cost:50' #The Level the enchantment is and the cost that level gives.
      - 'Level:2, Cost:135'
      - 'Level:3, Cost:200'
  #######################
  # Item:<ID:MD> - The item ID and Meta Data. Meta Data is optional.
  # Cost:<Number> - The amount of currency the player will get for selling it.
  # Currency:<XP_Level/XP_Total/<Custom Currency Name>> - The currency the player gets for selling it.
  # Example: - 'Item:311, Cost:4, Currency:Vault'
  #
  # Item Names can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  #######################
  Item-Cost:
    - 'Item:LOG:0, Cost:2, Currency:Vault'
    - 'Item:WOOL:0, Cost:0, Currency:Vault'
    - 'Item:LEAVES:0, Cost:1, Currency:Vault'
    - 'Item:SAPLING:0, Cost:0, Currency:Vault'
    - 'Item:STONE_BUTTON:0, Cost:6, Currency:Vault'
    - 'Item:WOOD:0, Cost:0, Currency:Vault'
    - 'Item:ARROW:0, Cost:3, Currency:Vault'
    - 'Item:DIAMOND_PICKAXE:0, Cost:650, Currency:Vault'
    - 'Item:RAW_FISH:0, Cost:5, Currency:Vault'
    - 'Item:MINECART:0, Cost:23, Currency:Vault'
    - 'Item:LEATHER_CHESTPLATE:0, Cost:85, Currency:Vault'
    - 'Item:STORAGE_MINECART:0, Cost:30, Currency:Vault'
    - 'Item:FEATHER:0, Cost:3, Currency:Vault'
    - 'Item:GOLD_CHESTPLATE:0, Cost:6, Currency:Vault'
    - 'Item:MUSHROOM_SOUP:0, Cost:4, Currency:Vault'
    - 'Item:BREAD:0, Cost:30, Currency:Vault'
    - 'Item:STATIONARY_WATER:0, Cost:1, Currency:Vault'
    - 'Item:WORKBENCH:0, Cost:2, Currency:Vault'
    - 'Item:STONE_HOE:0, Cost:2, Currency:Vault'
    - 'Item:BROWN_MUSHROOM:0, Cost:2, Currency:Vault'
    - 'Item:DIAMOND_HOE:0, Cost:400, Currency:Vault'
    - 'Item:WOOD_SWORD:0, Cost:1, Currency:Vault'
    - 'Item:TORCH:0, Cost:4, Currency:Vault'
    - 'Item:GRASS:0, Cost:1, Currency:Vault'
    - 'Item:POWERED_MINECART:0, Cost:32, Currency:Vault'
    - 'Item:SNOW_BALL:0, Cost:1, Currency:Vault'
    - 'Item:GOLDEN_APPLE:0, Cost:100, Currency:Vault'
    - 'Item:LEATHER_LEGGINGS:0, Cost:75, Currency:Vault'
    - 'Item:DIAMOND_AXE:0, Cost:650, Currency:Vault'
    - 'Item:SLIME_BALL:0, Cost:50, Currency:Vault'
    - 'Item:FENCE:0, Cost:1, Currency:Vault'
    - 'Item:STONE_SPADE:0, Cost:1, Currency:Vault'
    - 'Item:CLAY_BRICK:0, Cost:5, Currency:Vault'
    - 'Item:NOTE_BLOCK:0, Cost:36, Currency:Vault'
    - 'Item:IRON_AXE:0, Cost:22, Currency:Vault'
    - 'Item:COAL_ORE:0, Cost:15, Currency:Vault'
    - 'Item:CLAY_BALL:0, Cost:3, Currency:Vault'
    - 'Item:FISHING_ROD:0, Cost:10, Currency:Vault'
    - 'Item:IRON_HOE:0, Cost:22, Currency:Vault'
    - 'Item:GOLD_RECORD:0, Cost:100, Currency:Vault'
    - 'Item:IRON_PICKAXE:0, Cost:22, Currency:Vault'
    - 'Item:IRON_DOOR:0, Cost:22, Currency:Vault'
    - 'Item:BUCKET:0, Cost:22, Currency:Vault'
    - 'Item:RED_ROSE:0, Cost:2, Currency:Vault'
    - 'Item:GRILLED_PORK:0, Cost:7, Currency:Vault'
    - 'Item:GRAVEL:0, Cost:1, Currency:Vault'
    - 'Item:WOOD_DOOR:0, Cost:3, Currency:Vault'
    - 'Item:CHAINMAIL_HELMET:0, Cost:40, Currency:Vault'
    - 'Item:IRON_CHESTPLATE:0, Cost:22, Currency:Vault'
    - 'Item:DIAMOND_BLOCK:0, Cost:2000, Currency:Vault'
    - 'Item:DIAMOND_HELMET:0, Cost:1000, Currency:Vault'
    - 'Item:GOLD_HELMET:0, Cost:6, Currency:Vault'
    - 'Item:REDSTONE_TORCH_ON:0, Cost:32, Currency:Vault'
    - 'Item:IRON_SPADE:0, Cost:22, Currency:Vault'
    - 'Item:FURNACE:0, Cost:8, Currency:Vault'
    - 'Item:IRON_SWORD:0, Cost:22, Currency:Vault'
    - 'Item:DISPENSER:0, Cost:58, Currency:Vault'
    - 'Item:WOOD_AXE:0, Cost:2, Currency:Vault'
    - 'Item:SEEDS:0, Cost:2, Currency:Vault'
    - 'Item:PAINTING:0, Cost:25, Currency:Vault'
    - 'Item:WOOD_PLATE:0, Cost:1, Currency:Vault'
    - 'Item:REDSTONE_ORE:0, Cost:30, Currency:Vault'
    - 'Item:DIAMOND_SPADE:0, Cost:210, Currency:Vault'
    - 'Item:WATER_BUCKET:0, Cost:40, Currency:Vault'
    - 'Item:WATER:0, Cost:1, Currency:Vault'
    - 'Item:BEDROCK:0, Cost:100, Currency:Vault'
    - 'Item:IRON_DOOR_BLOCK:0, Cost:15, Currency:Vault'
    - 'Item:GOLD_HOE:0, Cost:6, Currency:Vault'
    - 'Item:SAND:0, Cost:1, Currency:Vault'
    - 'Item:GOLD_SWORD:0, Cost:6, Currency:Vault'
    - 'Item:STONE_AXE:0, Cost:3, Currency:Vault'
    - 'Item:BOOKSHELF:0, Cost:140, Currency:Vault'
    - 'Item:IRON_BLOCK:0, Cost:190, Currency:Vault'
    - 'Item:JACK_O_LANTERN:0, Cost:56, Currency:Vault'
    - 'Item:BOAT:0, Cost:3, Currency:Vault'
    - 'Item:DIAMOND_CHESTPLATE:0, Cost:1750, Currency:Vault'
    - 'Item:REDSTONE_WIRE:0, Cost:30, Currency:Vault'
    - 'Item:RED_MUSHROOM:0, Cost:2, Currency:Vault'
    - 'Item:STRING:0, Cost:5, Currency:Vault'
    - 'Item:STONE_PLATE:0, Cost:6, Currency:Vault'
    - 'Item:WALL_SIGN:0, Cost:1, Currency:Vault'
    - 'Item:CACTUS:0, Cost:10, Currency:Vault'
    - 'Item:SULPHUR:0, Cost:20, Currency:Vault'
    - 'Item:RAILS:0, Cost:22, Currency:Vault'
    - 'Item:IRON_ORE:0, Cost:18, Currency:Vault'
    - 'Item:LEATHER_HELMET:0, Cost:52, Currency:Vault'
    - 'Item:STONE:0, Cost:3, Currency:Vault'
    - 'Item:EGG:0, Cost:1, Currency:Vault'
    - 'Item:DIAMOND_ORE:0, Cost:200, Currency:Vault'
    - 'Item:WOOD_HOE:0, Cost:2, Currency:Vault'
    - 'Item:GOLD_LEGGINGS:0, Cost:6, Currency:Vault'
    - 'Item:CHAINMAIL_LEGGINGS:0, Cost:50, Currency:Vault'
    - 'Item:YELLOW_FLOWER:0, Cost:2, Currency:Vault'
    - 'Item:IRON_HELMET:0, Cost:22, Currency:Vault'
    - 'Item:OBSIDIAN:0, Cost:130, Currency:Vault'
    - 'Item:DIRT:0, Cost:1, Currency:Vault'
    - 'Item:LEATHER:0, Cost:10, Currency:Vault'
    - 'Item:LEATHER_BOOTS:0, Cost:42, Currency:Vault'
    - 'Item:LEVER:0, Cost:1, Currency:Vault'
    - 'Item:COBBLESTONE:0, Cost:1, Currency:Vault'
    - 'Item:CAKE:0, Cost:180, Currency:Vault'
    - 'Item:WOOD_STAIRS:0, Cost:1, Currency:Vault'
    - 'Item:IRON_INGOT:0, Cost:0, Currency:Vault'
    - 'Item:GOLD_ORE:0, Cost:45, Currency:Vault'
    - 'Item:PUMPKIN:0, Cost:50, Currency:Vault'
    - 'Item:BED:0, Cost:68, Currency:Vault'
    - 'Item:WATCH:0, Cost:6, Currency:Vault'
    - 'Item:IRON_LEGGINGS:0, Cost:22, Currency:Vault'
    - 'Item:SIGN:0, Cost:1, Currency:Vault'
    - 'Item:DOUBLE_STEP:0, Cost:1, Currency:Vault'
    - 'Item:WOOD_PICKAXE:0, Cost:2, Currency:Vault'
    - 'Item:STONE_PICKAXE:0, Cost:4, Currency:Vault'
    - 'Item:CHAINMAIL_BOOTS:0, Cost:30, Currency:Vault'
    - 'Item:DIAMOND_LEGGINGS:0, Cost:1500, Currency:Vault'
    - 'Item:COOKED_FISH:0, Cost:7, Currency:Vault'
    - 'Item:SADDLE:0, Cost:100, Currency:Vault'
    - 'Item:COBBLESTONE_STAIRS:0, Cost:1, Currency:Vault'
    - 'Item:TNT:0, Cost:100, Currency:Vault'
    - 'Item:GLOWING_REDSTONE_ORE:0, Cost:30, Currency:Vault'
    - 'Item:APPLE:0, Cost:10, Currency:Vault'
    - 'Item:WOOD_SPADE:0, Cost:1, Currency:Vault'
    - 'Item:GOLD_INGOT:0, Cost:105, Currency:Vault'
    - 'Item:DIODE:0, Cost:110, Currency:Vault'
    - 'Item:SOIL:0, Cost:1, Currency:Vault'
    - 'Item:CLAY:0, Cost:12, Currency:Vault'
    - 'Item:GOLD_BLOCK:0, Cost:450, Currency:Vault'
    - 'Item:STICK:0, Cost:0, Currency:Vault'
    - 'Item:PAPER:0, Cost:10, Currency:Vault'
    - 'Item:BRICK:0, Cost:21, Currency:Vault'
    - 'Item:STATIONARY_LAVA:0, Cost:1, Currency:Vault'
    - 'Item:CHEST:0, Cost:4, Currency:Vault'
    - 'Item:SANDSTONE:0, Cost:3, Currency:Vault'
    - 'Item:GOLD_PICKAXE:0, Cost:6, Currency:Vault'
    - 'Item:COMPASS:0, Cost:22, Currency:Vault'
    - 'Item:SUGAR_CANE:0, Cost:10, Currency:Vault'
    - 'Item:DIAMOND_SWORD:0, Cost:420, Currency:Vault'
    - 'Item:GOLD_BOOTS:0, Cost:6, Currency:Vault'
    - 'Item:STONE_SWORD:0, Cost:2, Currency:Vault'
    - 'Item:COAL:0, Cost:15, Currency:Vault'
    - 'Item:GOLD_AXE:0, Cost:6, Currency:Vault'
    - 'Item:BONE:0, Cost:2, Currency:Vault'
    - 'Item:DIAMOND:0, Cost:200, Currency:Vault'
    - 'Item:GLASS:0, Cost:3, Currency:Vault'
    - 'Item:GOLD_SPADE:0, Cost:6, Currency:Vault'
    - 'Item:LAPIS_BLOCK:0, Cost:950, Currency:Vault'
    - 'Item:LAVA_BUCKET:0, Cost:40, Currency:Vault'
    - 'Item:WHEAT:0, Cost:9, Currency:Vault'
    - 'Item:LADDER:0, Cost:0, Currency:Vault'
    - 'Item:SUGAR_CANE_BLOCK:0, Cost:15, Currency:Vault'
    - 'Item:BOWL:0, Cost:0, Currency:Vault'
    - 'Item:CHAINMAIL_CHESTPLATE:0, Cost:40, Currency:Vault'
    - 'Item:DIAMOND_BOOTS:0, Cost:850, Currency:Vault'
    - 'Item:LAPIS_ORE:0, Cost:100, Currency:Vault'
    - 'Item:LAVA:0, Cost:25, Currency:Vault'
    - 'Item:MILK_BUCKET:0, Cost:40, Currency:Vault'
    - 'Item:REDSTONE:0, Cost:32, Currency:Vault'
    - 'Item:GREEN_RECORD:0, Cost:100, Currency:Vault'
    - 'Item:INK_SACK:0, Cost:10, Currency:Vault'
    - 'Item:GLOWSTONE_DUST:0, Cost:10, Currency:Vault'
    - 'Item:BOOK:0, Cost:45, Currency:Vault'
    - 'Item:BOW:0, Cost:15, Currency:Vault'
    - 'Item:IRON_BOOTS:0, Cost:22, Currency:Vault'
    - 'Item:STEP:0, Cost:1, Currency:Vault'
    - 'Item:SUGAR:0, Cost:10, Currency:Vault'